(define (domain zeno-travel)
(:requirements :strips :typing)
(:types 	aircraft person city flevel - object
)

(:predicates (at-person ?p - person ?c - city)
	(at-aircraft ?a - aircraft ?c - city)
	(in ?pass - person ?plane - aircraft)
	(route-fly ?city1 - city ?city2 - city)
	(route-zoom ?city1 - city ?city2 - city)
	(fuel-level ?plane - aircraft ?level - flevel)
	(next ?level1 - flevel ?level2 - flevel)
)

(:action board
	:parameters   (?p - person ?a - aircraft ?c - city)
	:precondition (and )
	:effect       (and (at-aircraft ?a ?c)
		(in ?p ?a)
		(not (at-person ?p ?c)) 
		 
		))

(:action debark
	:parameters   (?p - person ?a - aircraft ?c - city)
	:precondition (or (and (at-aircraft ?a ?c))
	(and (in ?p ?a)))
	:effect       (and (at-aircraft ?a ?c)
		(at-person ?p ?c)
		(not (in ?p ?a)) 
		 
		))

(:action fly
	:parameters   (?a - aircraft ?c1 - city ?c2 - city ?l1 - flevel ?l2 - flevel)
	:precondition (or (and (at-aircraft ?a ?c1)
	(next ?l2 ?l1))
	(and (fuel-level ?a ?l1))
	(and (next ?l2 ?l1)
	(not (at-aircraft ?a ?c2)))
	(and (next ?l2 ?l1)
	(route-fly ?c1 ?c2))
	(and (next ?l2 ?l1)
	(route-fly ?c2 ?c1)))
	:effect       (and (at-aircraft ?a ?c2)
		(fuel-level ?a ?l2)
		(next ?l2 ?l1)
		(not (at-aircraft ?a ?c1))
		(not (fuel-level ?a ?l1))
		(not (next ?l1 ?l2))
		(not (route-zoom ?c1 ?c2))
		(not (route-zoom ?c2 ?c1))
		(route-fly ?c1 ?c2)
		(route-fly ?c2 ?c1) 
		 
		))

(:action zoom
	:parameters   (?a - aircraft ?c1 - city ?c2 - city ?l1 - flevel ?l2 - flevel ?l3 - flevel)
	:precondition (or (and (at-aircraft ?a ?c1)
	(fuel-level ?a ?l1)
	(next ?l3 ?l2))
	(and (at-aircraft ?a ?c1)
	(fuel-level ?a ?l1)
	(not (route-fly ?c1 ?c2)))
	(and (at-aircraft ?a ?c1)
	(fuel-level ?a ?l1)
	(not (route-fly ?c2 ?c1)))
	(and (at-aircraft ?a ?c1)
	(fuel-level ?a ?l1)
	(route-zoom ?c1 ?c2))
	(and (at-aircraft ?a ?c1)
	(fuel-level ?a ?l1)
	(route-zoom ?c2 ?c1))
	(and (at-aircraft ?a ?c1)
	(next ?l3 ?l2)
	(not (route-fly ?c1 ?c2)))
	(and (at-aircraft ?a ?c1)
	(next ?l3 ?l2)
	(not (route-fly ?c2 ?c1)))
	(and (at-aircraft ?a ?c1)
	(next ?l3 ?l2)
	(route-zoom ?c1 ?c2))
	(and (at-aircraft ?a ?c1)
	(next ?l3 ?l2)
	(route-zoom ?c2 ?c1))
	(and (fuel-level ?a ?l1)
	(next ?l2 ?l1)
	(next ?l3 ?l2))
	(and (fuel-level ?a ?l1)
	(next ?l2 ?l1)
	(route-zoom ?c1 ?c2))
	(and (fuel-level ?a ?l1)
	(next ?l2 ?l1)
	(route-zoom ?c2 ?c1))
	(and (fuel-level ?a ?l1)
	(next ?l3 ?l2)
	(not (at-aircraft ?a ?c2)))
	(and (fuel-level ?a ?l1)
	(not (at-aircraft ?a ?c2))
	(not (route-fly ?c1 ?c2)))
	(and (fuel-level ?a ?l1)
	(not (at-aircraft ?a ?c2))
	(not (route-fly ?c2 ?c1)))
	(and (fuel-level ?a ?l1)
	(not (at-aircraft ?a ?c2))
	(route-zoom ?c1 ?c2))
	(and (fuel-level ?a ?l1)
	(not (at-aircraft ?a ?c2))
	(route-zoom ?c2 ?c1))
	(and (next ?l2 ?l1)
	(next ?l3 ?l2)
	(not (next ?l1 ?l3)))
	(and (next ?l2 ?l1)
	(next ?l3 ?l2)
	(not (route-fly ?c1 ?c2)))
	(and (next ?l2 ?l1)
	(next ?l3 ?l2)
	(not (route-fly ?c2 ?c1)))
	(and (next ?l2 ?l1)
	(next ?l3 ?l2)
	(route-zoom ?c1 ?c2))
	(and (next ?l2 ?l1)
	(next ?l3 ?l2)
	(route-zoom ?c2 ?c1)))
	:effect       (and (at-aircraft ?a ?c2)
		(fuel-level ?a ?l3)
		(next ?l2 ?l1)
		(next ?l3 ?l2)
		(not (at-aircraft ?a ?c1))
		(not (fuel-level ?a ?l1))
		(not (fuel-level ?a ?l2))
		(not (next ?l1 ?l2))
		(not (next ?l1 ?l3))
		(not (next ?l2 ?l3))
		(not (next ?l3 ?l1))
		(not (route-fly ?c1 ?c2))
		(not (route-fly ?c2 ?c1))
		(route-zoom ?c1 ?c2)
		(route-zoom ?c2 ?c1) 
		 
		))

(:action refuel
	:parameters   (?a - aircraft ?c - city ?l - flevel ?l1 - flevel)
	:precondition (or (and (at-aircraft ?a ?c))
	(and (fuel-level ?a ?l)))
	:effect       (and (at-aircraft ?a ?c)
		(fuel-level ?a ?l1)
		(next ?l ?l1)
		(not (fuel-level ?a ?l))
		(not (next ?l1 ?l)) 
		 
		))

)