(define (domain robot-delivery)
(:requirements :typing :strips)
(:types 	package table - object
)

(:predicates (on ?p - package ?o - object)
	(clear ?p - package)
	(robot-empty )
	(holding ?p - package)
)

(:action pick-up
	:parameters   (?pkg - package ?t - table)
	:precondition (or (and (clear ?pkg))
	(and (on ?pkg ?t))
	(and (robot-empty )))
	:effect       (and (holding ?pkg)
		(not (clear ?pkg))
		(not (on ?pkg ?t))
		(not (robot-empty )) 
		 
		))

(:action put-down
	:parameters   (?pkg - package ?t - table)
	:precondition (or (and (holding ?pkg)
	(not (clear ?pkg))
	(not (on ?pkg ?t)))
	(and (holding ?pkg)
	(not (clear ?pkg)))
	(and (holding ?pkg)
	(not (on ?pkg ?t))
	(not (robot-empty )))
	(and (holding ?pkg)
	(not (on ?pkg ?t)))
	(and (holding ?pkg)
	(not (robot-empty )))
	(and (holding ?pkg))
	(and (not (clear ?pkg))
	(not (on ?pkg ?t))
	(not (robot-empty )))
	(and (not (clear ?pkg))
	(not (robot-empty ))))
	:effect       (and (clear ?pkg)
		(not (holding ?pkg))
		(on ?pkg ?t)
		(robot-empty ) 
		 
		))

(:action stack
	:parameters   (?pkg - package ?underpkg - package)
	:precondition (or (and (clear ?underpkg)
	(not (robot-empty )))
	(and (holding ?pkg)
	(not (clear ?pkg)))
	(and (holding ?pkg)
	(not (robot-empty )))
	(and (holding ?pkg))
	(and (not (clear ?pkg))
	(not (on ?underpkg ?pkg)))
	(and (not (clear ?pkg))
	(not (robot-empty )))
	(and (not (holding ?underpkg))
	(not (robot-empty ))))
	:effect       (and (clear ?pkg)
		(not (clear ?underpkg))
		(not (holding ?pkg))
		(not (holding ?underpkg))
		(not (on ?underpkg ?pkg))
		(on ?pkg ?underpkg)
		(robot-empty ) 
		 
		))

(:action unstack
	:parameters   (?pkg - package ?underpkg - package)
	:precondition (or (and (clear ?pkg)
	(not (clear ?underpkg))
	(on ?pkg ?underpkg))
	(and (clear ?pkg)
	(not (clear ?underpkg))
	(robot-empty ))
	(and (on ?pkg ?underpkg)))
	:effect       (and (clear ?underpkg)
		(holding ?pkg)
		(not (clear ?pkg))
		(not (holding ?underpkg))
		(not (on ?pkg ?underpkg))
		(not (on ?underpkg ?pkg))
		(not (robot-empty )) 
		 
		))

)