(define (domain grocery)
(:requirements :strips :typing)
(:types 	agent product_item compartment scale - object
)

(:predicates (at ?x - agent ?comp - compartment)
	(connected ?comp1 - compartment ?comp2 - compartment)
	(scale-at ?x - scale ?comp - compartment)
	(has-product ?comp - compartment ?prod - product_item)
	(left-hand-free ?x - agent)
	(right-hand-free ?x - agent)
	(holding-left ?x - agent ?prod - product_item)
	(holding-right ?x - agent ?prod - product_item)
	(ready-to-weigh ?p - product_item)
)

(:action move_0
	:parameters   (?a - agent ?c1 - compartment ?c2 - compartment)
	:precondition (and (at ?a ?c1))
	:effect       (and (at ?a ?c2)
		(not (at ?a ?c1)) 
		 
		))

(:action move_1
	:parameters   (?a - agent ?c1 - compartment ?c2 - compartment)
	:precondition (and (at ?a ?c1))
	:effect       (and (at ?a ?c2)
		(connected ?c1 ?c2)
		(not (at ?a ?c1)) 
		 
		))

(:action move_2
	:parameters   (?a - agent ?c1 - compartment ?c2 - compartment)
	:precondition (and (at ?a ?c1))
	:effect       (and (at ?a ?c2)
		(connected ?c2 ?c1)
		(not (at ?a ?c1)) 
		 
		))

(:action move_3
	:parameters   (?a - agent ?c1 - compartment ?c2 - compartment)
	:precondition (and (at ?a ?c1))
	:effect       (and (at ?a ?c2)
		(connected ?c1 ?c2)
		(connected ?c2 ?c1)
		(not (at ?a ?c1)) 
		 
		))

(:action pick-up-right_0
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c)
	(not (ready-to-weigh ?p)))
	(and (has-product ?c ?p))
	(and (right-hand-free ?a)))
	:effect       (and (holding-right ?a ?p)
		(not (has-product ?c ?p))
		(not (right-hand-free ?a)) 
		 
		))

(:action pick-up-right_1
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c)
	(not (ready-to-weigh ?p)))
	(and (has-product ?c ?p))
	(and (right-hand-free ?a)))
	:effect       (and (at ?a ?c)
		(holding-right ?a ?p)
		(not (has-product ?c ?p))
		(not (right-hand-free ?a)) 
		 
		))

(:action pick-up-right_2
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c)
	(not (ready-to-weigh ?p)))
	(and (has-product ?c ?p))
	(and (right-hand-free ?a)))
	:effect       (and (holding-right ?a ?p)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (right-hand-free ?a)) 
		 
		))

(:action pick-up-right_3
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c)
	(not (ready-to-weigh ?p)))
	(and (has-product ?c ?p))
	(and (right-hand-free ?a)))
	:effect       (and (holding-right ?a ?p)
		(not (has-product ?c ?p))
		(not (ready-to-weigh ?p))
		(not (right-hand-free ?a)) 
		 
		))

(:action pick-up-right_4
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c)
	(not (ready-to-weigh ?p)))
	(and (has-product ?c ?p))
	(and (right-hand-free ?a)))
	:effect       (and (at ?a ?c)
		(holding-right ?a ?p)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (right-hand-free ?a)) 
		 
		))

(:action pick-up-right_5
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c)
	(not (ready-to-weigh ?p)))
	(and (has-product ?c ?p))
	(and (right-hand-free ?a)))
	:effect       (and (at ?a ?c)
		(holding-right ?a ?p)
		(not (has-product ?c ?p))
		(not (ready-to-weigh ?p))
		(not (right-hand-free ?a)) 
		 
		))

(:action pick-up-right_6
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c)
	(not (ready-to-weigh ?p)))
	(and (has-product ?c ?p))
	(and (right-hand-free ?a)))
	:effect       (and (holding-right ?a ?p)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (ready-to-weigh ?p))
		(not (right-hand-free ?a)) 
		 
		))

(:action pick-up-right_7
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c)
	(not (ready-to-weigh ?p)))
	(and (has-product ?c ?p))
	(and (right-hand-free ?a)))
	:effect       (and (at ?a ?c)
		(holding-right ?a ?p)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (ready-to-weigh ?p))
		(not (right-hand-free ?a)) 
		 
		))

(:action pick-up-left_0
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c))
	(and (has-product ?c ?p)))
	:effect       (and (holding-left ?a ?p)
		(not (has-product ?c ?p))
		(not (left-hand-free ?a)) 
		 
		))

(:action pick-up-left_1
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c))
	(and (has-product ?c ?p)))
	:effect       (and (at ?a ?c)
		(holding-left ?a ?p)
		(not (has-product ?c ?p))
		(not (left-hand-free ?a)) 
		 
		))

(:action pick-up-left_2
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c))
	(and (has-product ?c ?p)))
	:effect       (and (holding-left ?a ?p)
		(not (has-product ?c ?p))
		(not (left-hand-free ?a))
		(not (ready-to-weigh ?p)) 
		 
		))

(:action pick-up-left_3
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c))
	(and (has-product ?c ?p)))
	:effect       (and (holding-left ?a ?p)
		(not (has-product ?c ?p))
		(not (holding-right ?a ?p))
		(not (left-hand-free ?a)) 
		 
		))

(:action pick-up-left_4
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c))
	(and (has-product ?c ?p)))
	:effect       (and (at ?a ?c)
		(holding-left ?a ?p)
		(not (has-product ?c ?p))
		(not (left-hand-free ?a))
		(not (ready-to-weigh ?p)) 
		 
		))

(:action pick-up-left_5
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c))
	(and (has-product ?c ?p)))
	:effect       (and (at ?a ?c)
		(holding-left ?a ?p)
		(not (has-product ?c ?p))
		(not (holding-right ?a ?p))
		(not (left-hand-free ?a)) 
		 
		))

(:action pick-up-left_6
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c))
	(and (has-product ?c ?p)))
	:effect       (and (holding-left ?a ?p)
		(not (has-product ?c ?p))
		(not (holding-right ?a ?p))
		(not (left-hand-free ?a))
		(not (ready-to-weigh ?p)) 
		 
		))

(:action pick-up-left_7
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c))
	(and (has-product ?c ?p)))
	:effect       (and (at ?a ?c)
		(holding-left ?a ?p)
		(not (has-product ?c ?p))
		(not (holding-right ?a ?p))
		(not (left-hand-free ?a))
		(not (ready-to-weigh ?p)) 
		 
		))

(:action place-on-scale-right_0
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a) 
		 
		))

(:action place-on-scale-right_1
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (at ?a ?c)
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a) 
		 
		))

(:action place-on-scale-right_2
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-right_3
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a) 
		 
		))

(:action place-on-scale-right_4
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (not (has-product ?c ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a) 
		 
		))

(:action place-on-scale-right_5
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (at ?a ?c)
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-right_6
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (at ?a ?c)
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a) 
		 
		))

(:action place-on-scale-right_7
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (at ?a ?c)
		(not (has-product ?c ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a) 
		 
		))

(:action place-on-scale-right_8
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-right_9
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (not (has-product ?c ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-right_10
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a) 
		 
		))

(:action place-on-scale-right_11
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (at ?a ?c)
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-right_12
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (at ?a ?c)
		(not (has-product ?c ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-right_13
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (at ?a ?c)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a) 
		 
		))

(:action place-on-scale-right_14
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-right_15
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (and (holding-right ?a ?p))
	:effect       (and (at ?a ?c)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_0
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (holding-left ?a ?p))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_1
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (holding-left ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_2
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_3
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (holding-left ?a ?p))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_4
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (holding-left ?a ?p))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_5
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_6
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_7
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (holding-left ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_8
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (holding-left ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_9
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_10
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_11
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_12
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_13
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (holding-left ?a ?p))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_14
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_15
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_16
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_17
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_18
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_19
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (holding-left ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_20
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_21
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_22
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_23
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_24
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_25
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_26
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_27
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p) 
		 
		))

(:action place-on-scale-left_28
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_29
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_30
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left_31
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p))
	(and (not (has-product ?c ?p))
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a)))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(left-hand-free ?a)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(not (right-hand-free ?a))
		(ready-to-weigh ?p)
		(scale-at ?s ?c) 
		 
		))

)