(define (domain grocery)
(:requirements :typing :strips)
(:types 	agent product_item compartment scale - object
)

(:predicates (at ?x - agent ?comp - compartment)
	(connected ?comp1 - compartment ?comp2 - compartment)
	(scale-at ?x - scale ?comp - compartment)
	(has-product ?comp - compartment ?prod - product_item)
	(left-hand-free ?x - agent)
	(right-hand-free ?x - agent)
	(holding-left ?x - agent ?prod - product_item)
	(holding-right ?x - agent ?prod - product_item)
	(ready-to-weigh ?p - product_item)
)

(:action move
	:parameters   (?a - agent ?c1 - compartment ?c2 - compartment)
	:precondition (or (and (at ?a ?c1)
	(connected ?c1 ?c2))
	(and (at ?a ?c1)
	(connected ?c2 ?c1))
	(and (connected ?c1 ?c2)
	(not (at ?a ?c2)))
	(and (connected ?c2 ?c1)
	(not (at ?a ?c2))))
	:effect       (and (at ?a ?c2)
		(connected ?c1 ?c2)
		(connected ?c2 ?c1)
		(not (at ?a ?c1)) 
		 
		))

(:action pick-up-right
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (and (at ?a ?c)
	(has-product ?c ?p))
	:effect       (and (at ?a ?c)
		(holding-right ?a ?p)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (ready-to-weigh ?p))
		(not (right-hand-free ?a)) 
		 
		))

(:action pick-up-left
	:parameters   (?a - agent ?c - compartment ?p - product_item)
	:precondition (or (and (at ?a ?c)
	(has-product ?c ?p)
	(right-hand-free ?a))
	(and (at ?a ?c)
	(has-product ?c ?p))
	(and (at ?a ?c)
	(right-hand-free ?a))
	(and (at ?a ?c)))
	:effect       (and (at ?a ?c)
		(holding-left ?a ?p)
		(not (has-product ?c ?p))
		(not (holding-right ?a ?p))
		(not (left-hand-free ?a))
		(not (ready-to-weigh ?p))
		(right-hand-free ?a) 
		 
		))

(:action place-on-scale-right
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(holding-right ?a ?p)
	(not (ready-to-weigh ?p))
	(scale-at ?s ?c))
	(and (at ?a ?c)
	(holding-right ?a ?p)
	(scale-at ?s ?c))
	(and (at ?a ?c)
	(not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c))
	(and (at ?a ?c)
	(not (ready-to-weigh ?p))
	(scale-at ?s ?c))
	(and (at ?a ?c)
	(not (right-hand-free ?a))
	(scale-at ?s ?c))
	(and (holding-right ?a ?p)
	(not (ready-to-weigh ?p))
	(scale-at ?s ?c))
	(and (holding-right ?a ?p)
	(scale-at ?s ?c))
	(and (not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(scale-at ?s ?c))
	(and (not (right-hand-free ?a))
	(scale-at ?s ?c)))
	:effect       (and (at ?a ?c)
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(ready-to-weigh ?p)
		(right-hand-free ?a)
		(scale-at ?s ?c) 
		 
		))

(:action place-on-scale-left
	:parameters   (?a - agent ?p - product_item ?c - compartment ?s - scale)
	:precondition (or (and (at ?a ?c)
	(has-product ?c ?p)
	(not (at ?a ?c)))
	(and (at ?a ?c)
	(has-product ?c ?p)
	(not (has-product ?c ?p)))
	(and (at ?a ?c)
	(holding-left ?a ?p)
	(not (at ?a ?c)))
	(and (at ?a ?c)
	(holding-right ?a ?p)
	(not (at ?a ?c)))
	(and (at ?a ?c)
	(left-hand-free ?a)
	(not (left-hand-free ?a)))
	(and (at ?a ?c)
	(not (at ?a ?c))
	(not (left-hand-free ?a)))
	(and (at ?a ?c)
	(not (at ?a ?c))
	(not (ready-to-weigh ?p)))
	(and (at ?a ?c)
	(not (at ?a ?c))
	(not (right-hand-free ?a)))
	(and (at ?a ?c)
	(not (at ?a ?c))
	(scale-at ?s ?c))
	(and (at ?a ?c)
	(not (at ?a ?c)))
	(and (at ?a ?c)
	(not (right-hand-free ?a))
	(right-hand-free ?a))
	(and (at ?a ?c)
	(not (scale-at ?s ?c))
	(scale-at ?s ?c))
	(and (has-product ?c ?p)
	(holding-left ?a ?p)
	(not (has-product ?c ?p)))
	(and (has-product ?c ?p)
	(holding-right ?a ?p)
	(not (has-product ?c ?p)))
	(and (has-product ?c ?p)
	(left-hand-free ?a)
	(not (left-hand-free ?a)))
	(and (has-product ?c ?p)
	(not (has-product ?c ?p))
	(not (left-hand-free ?a)))
	(and (has-product ?c ?p)
	(not (has-product ?c ?p))
	(not (right-hand-free ?a)))
	(and (has-product ?c ?p)
	(not (has-product ?c ?p))
	(ready-to-weigh ?p))
	(and (has-product ?c ?p)
	(not (has-product ?c ?p))
	(scale-at ?s ?c))
	(and (has-product ?c ?p)
	(not (has-product ?c ?p)))
	(and (has-product ?c ?p)
	(not (ready-to-weigh ?p))
	(ready-to-weigh ?p))
	(and (has-product ?c ?p)
	(not (right-hand-free ?a))
	(right-hand-free ?a))
	(and (has-product ?c ?p)
	(not (scale-at ?s ?c))
	(scale-at ?s ?c))
	(and (holding-left ?a ?p)
	(left-hand-free ?a)
	(not (left-hand-free ?a)))
	(and (holding-left ?a ?p)
	(not (ready-to-weigh ?p))
	(ready-to-weigh ?p))
	(and (holding-left ?a ?p)
	(not (right-hand-free ?a))
	(right-hand-free ?a))
	(and (holding-left ?a ?p)
	(not (scale-at ?s ?c))
	(scale-at ?s ?c))
	(and (holding-left ?a ?p))
	(and (holding-right ?a ?p)
	(left-hand-free ?a)
	(not (left-hand-free ?a)))
	(and (holding-right ?a ?p)
	(not (ready-to-weigh ?p))
	(ready-to-weigh ?p))
	(and (holding-right ?a ?p)
	(not (right-hand-free ?a))
	(right-hand-free ?a))
	(and (holding-right ?a ?p)
	(not (scale-at ?s ?c))
	(scale-at ?s ?c))
	(and (holding-right ?a ?p))
	(and (left-hand-free ?a)
	(not (left-hand-free ?a))
	(not (ready-to-weigh ?p)))
	(and (left-hand-free ?a)
	(not (left-hand-free ?a))
	(not (right-hand-free ?a)))
	(and (left-hand-free ?a)
	(not (left-hand-free ?a))
	(not (scale-at ?s ?c)))
	(and (left-hand-free ?a)
	(not (left-hand-free ?a)))
	(and (left-hand-free ?a)
	(not (scale-at ?s ?c))
	(scale-at ?s ?c))
	(and (not (at ?a ?c))
	(not (ready-to-weigh ?p))
	(ready-to-weigh ?p))
	(and (not (left-hand-free ?a))
	(not (ready-to-weigh ?p))
	(ready-to-weigh ?p))
	(and (not (left-hand-free ?a))
	(not (right-hand-free ?a))
	(right-hand-free ?a))
	(and (not (ready-to-weigh ?p))
	(not (right-hand-free ?a))
	(ready-to-weigh ?p))
	(and (not (ready-to-weigh ?p))
	(not (scale-at ?s ?c))
	(scale-at ?s ?c))
	(and (not (ready-to-weigh ?p))
	(ready-to-weigh ?p)
	(scale-at ?s ?c))
	(and (not (ready-to-weigh ?p))
	(ready-to-weigh ?p))
	(and (not (right-hand-free ?a))
	(not (scale-at ?s ?c))
	(scale-at ?s ?c))
	(and (not (right-hand-free ?a))
	(ready-to-weigh ?p)
	(right-hand-free ?a))
	(and (not (right-hand-free ?a))
	(right-hand-free ?a)
	(scale-at ?s ?c))
	(and (not (right-hand-free ?a))
	(right-hand-free ?a))
	(and (not (scale-at ?s ?c))
	(scale-at ?s ?c))
	(and ))
	:effect       (and (at ?a ?c)
		(has-product ?c ?p)
		(holding-left ?a ?p)
		(holding-right ?a ?p)
		(left-hand-free ?a)
		(not (at ?a ?c))
		(not (has-product ?c ?p))
		(not (holding-left ?a ?p))
		(not (holding-right ?a ?p))
		(not (left-hand-free ?a))
		(not (ready-to-weigh ?p))
		(not (right-hand-free ?a))
		(not (scale-at ?s ?c))
		(ready-to-weigh ?p)
		(right-hand-free ?a)
		(scale-at ?s ?c) 
		 
		))

)